export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const START_INGREDIENT_FETCH = "START_INGREDIENT_FETCH";

export const START_ORDER = "START_ORDER";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILED = "ORDER_FAILED";
export const PURCHASE_STATUS = "PURCHASE_STATUS";


export const START_ORDERS_FETCH = "START_ORDERS_FETCH"
export const ORDERS_FETCH_SUCCESS = "ORDERS_FETCH_SUCCESS"
export const ORDERS_FETCH_FAILED = "ORDERS_FETCH_FAILED"


export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const LOG_OUT = "LOG_OUT";